-- CREATE TABLE IF NOT EXISTS users (
--     user_id INTEGER PRIMARY KEY,
--     first_name TEXT NOT NULL,
--     last_name TEXT NOT NUll,
--     middle_name TEXT NOT NULL,
--     user_level TEXT DEFAULT 'user',
--     pass_word TEXT NOT NULL 
-- );

-- CREATE TABLE IF NOT EXISTS household (
--     household_id INTEGER NOT NULL,
--     family_id INTEGER NOT NULL,
--     household_address TEXT, 
--     no_of_families INTEGER,
--     PRIMARY KEY (household_id, family_id)
-- );

-- CREATE TABLE IF NOT EXISTS resident (
--     resident_id INTEGER PRIMARY KEY,
--     first_name TEXT NOT NULL,
--     last_name TEXT NOT NUll,
--     middle_name TEXT NOT NULL,
--     occupation TEXT NOT NULL,
--     date_of_birth DATE NOT NULL,
--     sex char(1) NOT NULL,
--     civil_status TEXT NOT NULL,
--     citizenship TEXT NOT NULL,
--     contact_num TEXT,
--     educ_attainment TEXT,
--     role_in_family TEXT
--     remarks TEXT,
--     family_id INTEGER REFERENCES household(family_id),
--     household_id INTEGER REFERENCES household(household_id)
-- );

-- CREATE TABLE IF NOT EXISTS certification_request_form (
--     request_id INTEGER PRIMARY KEY,
--     resident_id INTEGER REFERENCES resident(resident_id),
--     date_requested DATE DEFAULT CURRENT_DATE,
--     form_status TEXT NOT NULL,
--     user_id INTEGER REFERENCES users(user_id)
-- );

-- CREATE TABLE IF NOT EXISTS certification_form (
--     certification_id INTEGER PRIMARY KEY,
--     request_id INTEGER REFERENCES certification_request_form(request_id),
--     resident_id INTEGER REFERENCES resident(resident_id),
--     date_issued DATE DEFAULT CURRENT_DATE,
--     cert_type TEXT NOT NULL,
--     purpose TEXT NOT NULL
-- );
